openimis/openimis-be-contribution_plan_py

contribution_plan/__init__.py
contribution_plan/models.py
contribution_plan/services.py
contribution_plan/urls.py

TICKET: [OFS-15](https://openimis.atlassian.net/browse/OFS-15)

 OFS-15: Added models and services shell

---

contribution_plan/models.py
contribution_plan/tests.py
contribution_plan/tests/__init__.py
contribution_plan/tests/helpers.py
contribution_plan/tests/helpers_tests.py

TICKET: part of creating shell backend [OFS-15](https://openimis.atlassian.net/browse/OFS-15)

OFS-15: Improve models, add test helpers

---

contribution_plan/tests/gql_tests/query_tests.py
contribution_plan/tests/helpers.py

In that pull requests I want to merge tests written for checking graphQl queries. And I added "Calculation" relations in models tests of ContributionPlan  module after implementing shell backend for 'Calculation' module.

OFS-58: tests for ContributionPlan

---

README.md
contribution_plan/apps.py

In that pull request I want to merge the settings related with permissions etc and updated readme.md about CP and CPB module with basic informations.

OFS-123: settings and readme.md

---

setup.py

In that PR I want update setup.py file. Related to test server issue

OFS-156: adding install requires

---

contribution_plan/schema.py

In that PR I want to fix quickly the issue reported from @rstencel with replacing CP. Similar issue as https://github.com/openimis/openimis-be-policyholder_py/pull/21 in PolicyHolder.

OFS-156: hotfix - id instead of uuid in Mutation log in signal

---

contribution_plan/gql/gql_types.py
contribution_plan/schema.py

In that pull request I want to fix issue with filtering in CP and CPB module (dae_valid_from and date_valid_to) according to the new filters from Core module.

OFS-159: fixing in CP and CPB date filtering validity

---

contribution_plan/schema.py

Ticket - https://openimis.atlassian.net/browse/OFS-254 - issue 1 
In that PR I want to fix default validity filter for CP module

OFS-254: fixing validity filtering in CP module

---

contribution_plan/schema.py

Fixing issue reported by @rstencel

OFS-254: distinct after filtering product, calculation in CPB

---

contribution_plan/migrations/0009_contributionplan_roles_for_admin.py

TICKET: https://openimis.atlassian.net/browse/OP-461

OP-461: added migration script to apply roles for admin for that module

---

contribution_plan/migrations/0010_payment_plan_roles_for_admin.py

part of TICKET: https://openimis.atlassian.net/browse/OPL-50

OPL-50: added migration to add roles PaymentPlan for imis admin

---

contribution_plan/apps.py
contribution_plan/tests/gql_tests/query_tests.py

TICKET: https://openimis.atlassian.net/browse/OP-476

OP-476: fixed broken test with anonymous user context in contribution plan

---

contribution_plan/gql/gql_mutations/contribution_plan_bundle_mutations.py

TICKET: https://openimis.atlassian.net/browse/OP-745

OP-745: fix issue on ContributionPlanBundle edit - dateValidTo

---

contribution_plan/gql/gql_mutations/contribution_plan_bundle_mutations.py
contribution_plan/schema.py

TICKET: https://openimis.atlassian.net/browse/OP-762

OP-762: Moved Null 'validity_to' assigment to the 'core'

---

contribution_plan/utils.py

part of TICKET: https://openimis.atlassian.net/browse/OTC-594
moved 'obtain params' from json_ext.

OTC-594: moved obtain calcrule params into ContributionPlan

---

contribution_plan/migrations/0001_initial.py
contribution_plan/migrations/0008_historicalpaymentplan_paymentplan.py
contribution_plan/migrations/0009_contributionplan_roles_for_admin.py
contribution_plan/migrations/0010_payment_plan_roles_for_admin.py

Django 3.1

---

contribution_plan/tests/gql_tests/mutations_cp_tests.py
contribution_plan/tests/gql_tests/mutations_cpb_tests.py
contribution_plan/tests/gql_tests/mutations_cpbd_tests.py
contribution_plan/tests/gql_tests/mutations_pp_tests.py
contribution_plan/tests/gql_tests/query_tests.py
contribution_plan/tests/helpers.py
contribution_plan/tests/helpers_tests.py
contribution_plan/tests/services/services_cp_tests.py

[https://openimis.atlassian.net/browse/OP-868](https://openimis.atlassian.net/browse/OP-868)
Changes:
- Changed handling of JSON fields from JSON strings to python dictionaties (Django 3.2 update)
- Fixed TestCase handling (added all missing calls to super.setUpClass, super.setUp, removed unecessary teardowns)
- Removed some unused code/comments/imports
- Fixed code formatting

OP-868 Fix CI issues caused by Django 3.2 update

---

.github/workflows/openmis-module-test.yml
.github/workflows/python-publish.yml
contribution_plan/gql/gql_mutations/input_types.py
contribution_plan/models.py

Ticket:
https://openimis.atlassian.net/browse/OTC-730
Changes:
- added missing input field for replacing contribution plan

OTC-730: added missing input field for replacing contribution plan

---

contribution_plan/gql/gql_mutations/contribution_plan_bundle_mutations.py
contribution_plan/schema.py
contribution_plan/services.py
contribution_plan/tests/gql_tests/mutations_cpb_tests.py
contribution_plan/tests/services/services_cp_tests.py

Ticket: https://openimis.atlassian.net/browse/OTC-975
Changes:
- Added query for FE validation.
- BE blocks creating contribution plan with existing code.

OTC-975: Contribution plan bundle validation.

---

contribution_plan/gql/gql_mutations/input_types.py
contribution_plan/tests/gql_tests/mutations_cpb_tests.py

Ticket:
https://openimis.atlassian.net/browse/OP-1358
Changes:
- added code field to contribution plan bundle update payload

OP-1358: added code field for mutation update

---

contribution_plan/gql/gql_mutations/input_types.py
contribution_plan/tests/gql_tests/mutations_cpb_tests.py

Reverts openimis/openimis-be-contribution_plan_py#53

Revert "OP-1358: added code field for mutation update"

---

.github/workflows/openmis-module-test.yml
.github/workflows/python-publish.yml
contribution_plan/gql/gql_mutations/contribution_plan_bundle_details_mutations.py
contribution_plan/gql/gql_mutations/contribution_plan_bundle_mutations.py
contribution_plan/gql/gql_mutations/contribution_plan_mutations.py
contribution_plan/gql/gql_mutations/input_types.py
contribution_plan/gql/gql_mutations/payment_plan_mutations.py
contribution_plan/models.py
contribution_plan/schema.py
contribution_plan/services.py
contribution_plan/tests/gql_tests/mutations_cp_tests.py
contribution_plan/tests/gql_tests/mutations_cpb_tests.py
contribution_plan/tests/services/services_cp_tests.py

MERGING RELEASE branches
Release release/23.04

MERGING RELEASE branches

---

contribution_plan/schema.py

https://openimis.atlassian.net/browse/OP-1366
This PR will add show history option to payment plans, contribution plans, and contribution plan bundles. 
It is related to: https://github.com/openimis/openimis-fe-contribution_plan_js/pull/52

OP-1366: add show history option

---

contribution_plan/apps.py

https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.

OP-1518: load config

---

contribution_plan/gql/gql_mutations/payment_plan_mutations.py

https://openimis.atlassian.net/browse/CM-771
(we cannot update code on frontend level)

CM-771: remove redundant check for uniqueness of code (we cannot update code on frontend level)

---

contribution_plan/gql/gql_mutations/payment_plan_mutations.py
contribution_plan/services.py

MERGING develop into release/24.04

MERGING develop into release/24.04
